name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd 
          ls 
      - name: simple javascript action
        id: greet
        uses: reddyfull/githubactions-test-actions@v1
        with: 
          who-to-greet: Sri
      - name: Log Greeting time    
        run: echo "${{ steps.greet.outputs.time }}"